Repository manchenkoff/nuxt-auth-sanctum, pull requests merged in 2024-04, with the labels that each got.

#68 docs: use new `nuxi module add` command in installation
  README.md
Labels: documentation

#71 fix: prevent infinite redirect for guests
  src/runtime/httpFactory.ts
Labels: bug

#76 feat: add module logger with optional configuration
  playground/nuxt.config.ts
  src/constants.ts
  src/module.ts
  src/runtime/composables/useSanctumUser.ts
  src/runtime/httpFactory.ts
  src/runtime/plugin.ts
  src/types.ts
Labels: enhancement

#77 fix: prevent multiple identity requests on init
  package.json
  src/runtime/httpFactory.ts
  src/runtime/plugin.ts
Labels: enhancement

#79 feat: added publish workflow
  .github/workflows/publish.yml
  package.json
Labels: enhancement

#83 feat!: added guest mode for global middleware
  playground/nuxt.config.ts
  src/index.d.ts
  src/runtime/middleware/sanctum.global.ts
  src/types.ts
Labels: documentation, enhancement
